# Generated by Django 2.0.7 on 2019-04-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='playersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('Club', models.TextField()),
                ('Strength', models.TextField(default='Filled with Skill!')),
                ('summary', models.TextField(default='This is cool!')),
            ],
        ),
    ]
