# Generated by Django 2.0.7 on 2019-04-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_auto_20190418_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersinfo',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media/'),
        ),
    ]
